name: Release workflow for tagged versions
on:
  release:
    types:
      - created

jobs:
  push-store-image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pgversion: ['11', '12', '13', '14', '15']
        pgdistribution: ['rhpg', 'pg']
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build postgres image'
        run: |
          cd ${{ matrix.pgdistribution}}
          docker build . --build-arg="PGVERSION=${{ matrix.pgversion }}" --tag postgres
          docker tag postgres ghcr.io/tuskforce/${{ matrix.pgdistribution }}:${{ matrix.pgversion }}
          docker tag postgres ghcr.io/tuskforce/${{ matrix.pgdistribution }}:${{ matrix.pgversion }}-${{ github.ref_name }}

      - name: 'Tag latest'
        run: |
          docker tag postgres ghcr.io/tuskforce/${{ matrix.pgdistribution }}:latest
          docker tag postgres ghcr.io/tuskforce/postgres:${{ github.ref_name }}
        if: ${{ matrix.pgversion == '15' }}

      - name: 'Push to ghcr.io'
        run: docker push -a ghcr.io/tuskforce/${{ matrix.pgdistribution }}

      - name: 'Build pgbuilder image'
        run: |
          cd ${{ matrix.pgdistribution}}builder
          docker build . --build-arg="PGVERSION=${{ matrix.pgversion }}" --tag builder
          docker tag builder ghcr.io/tuskforce/${{ matrix.pgdistribution}}builder:${{ matrix.pgversion }}
          docker tag builder ghcr.io/tuskforce/${{ matrix.pgdistribution}}builder:${{ matrix.pgversion }}-${{ github.ref_name }}

      - name: 'Tag latest'
        run: |
          docker tag builder ghcr.io/tuskforce/${{ matrix.pgdistribution}}builder:latest
          docker tag builder ghcr.io/tuskforce/${{ matrix.pgdistribution}}builder:${{ github.ref_name }}
        if: ${{ matrix.pgversion == '15' }}

      - name: 'Push to ghcr.io'
        run: docker push -a ghcr.io/tuskforce/${{ matrix.pgdistribution}}builder
